### ISSUE TITLE
Processing of CSS as Sass breaks many tests

### ISSUE THREAD

**Issue by lunelson** [penman/SassUnit#12]
So, from looking at your code, I gather you're running the `*.css` file through Sass as well as the `*.scss` file in order to ensure the `output-style` (i.e. indentation) is consistent... unfortunately this comes with the side-effect that certain kinds of output can't be tested: for example if I inspect a map, I get an output that when run back through Sass again will generate an error. The same, if I am trying to output an unquoted string which would otherwise be an evaluable expression:

```scss
.test { 
  invalid-css: inspect((a: 1, b: 2));
  invalid-sass: unquote('3em + 4px');
} 
```
```css
/* the following cannot be run through Sass again; but I do need to test for this 😬 */
.test {
  invalid-css: (a: 1, b: 2);
  invalid-sass: 3em + 4px;
}
```
