### ISSUE TITLE
A way to test @error

### ISSUE THREAD

**Issue by athaeryn** [penman/SassUnit#9]
Is there a way to test that an @error is thrown?

We have a function that checks if a parameter is in a map, and throws an error if it isn't so that typos don't go unnoticed.

**Comment by lunelson** [comment]
This is an old issue but FWIW you need to abstract the error-throwing so you can conditionally store the error message. The following is what I use

```scss
//                           _   _
//                          | | | |
//  ___  __ _ ___ ___ ______| |_| |__  _ __ _____      __
// / __|/ _` / __/ __|______| __| '_ \| '__/ _ \ \ /\ / /
// \__ \ (_| \__ \__ \      | |_| | | | | | (_) \ V  V /
// |___/\__,_|___/___/       \__|_| |_|_|  \___/ \_/\_/

$errors: ();
$debugs: ();
$warns: ();

$catch: false !default;

@function error($msg) {
  @if $catch { $errors: append($errors, $msg) !global; }
  @else { @error '#{$msg}'; }
  @return null;
}

@function debug($msg) {
  @if $catch { $debugs: append($debugs, $msg) !global; }
  @else { @debug '#{$msg}'; }
  @return null;
}

@function warn($msg) {
  @if $catch { $warns: append($warns, $msg) !global; }
  @else { @warn '#{$msg}'; }
  @return null;
}

@mixin error($msg) { @at-root .throw { error: error($msg); } }
@mixin debug($msg) { @at-root .throw { debug: debug($msg); } }
@mixin warn($msg) { @at-root .throw { warn: warn($msg); } }

@function nth-last-error($n: 1) { @return nth($errors, length($errors) + 1 - $n); }
@function nth-last-debug($n: 1) { @return nth($debugs, length($debugs) + 1 - $n); }
@function nth-last-warn($n: 1) { @return nth($warns, length($warns) + 1 - $n); }

@function last-error() { @return nth-last-error(); }
@function last-debug() { @return nth-last-debug(); }
@function last-warn() { @return nth-last-warn(); }
```
then you merely do this:
```scss
$catch: true;

.test {
  throw: error('something went wrong');
  check: last-error();
}
```
and you will get this
```css
.test {
  check: "something went wrong";
}
```
